# Generated by Django 6.0.8 on 2026-08-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, verbose_name="Номер")),
                ("floor", models.IntegerField(verbose_name="Этаж")),
                ("workspace_type", models.CharField(max_length=50, verbose_name="Тип")),
            ],
        ),
    ]
