# Generated by Django 6.0.8 on 2026-08-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspace",
            options={
                "verbose_name": "Рабочее место",
                "verbose_name_plural": "Рабочее место",
            },
        ),
    ]
