# Generated by Django 6.0.8 on 2026-08-07 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="experience",
        ),
        migrations.AddField(
            model_name="employee",
            name="hired_at",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата трудоустройства"
            ),
        ),
    ]
