# Generated by Django 6.0.8 on 2026-08-09 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_remove_employee_experience_employee_hired_at"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_employee",
                to="workspaces.workspace",
                verbose_name="Рабочее место",
            ),
        ),
    ]
