# Generated by Django 6.0.8 on 2026-08-11 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_skill_employeeskill_employee_skills_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="employees/photos/", verbose_name="Фотография"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото сотрудника",
                "verbose_name_plural": "Фотографии сотрудников",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "order"), name="unique_employee_photo_order"
                    )
                ],
            },
        ),
    ]
