# Generated by Django 6.0.8 on 2026-08-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employeephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("backend", "Бэкенд-разработчик"),
                    ("frontend", "Фронтэнд-разработчик"),
                    ("tester", "Тестировщик"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
