# Generated by Django 6.0.8 on 2026-08-12 11:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_employee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Описание"
            ),
        ),
    ]
