# Generated by Django 6.0.8 on 2026-08-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_alter_employee_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeephoto",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="employees.employee",
                verbose_name="Сотрудник",
            ),
        ),
    ]
